name: "Test and Deploy"
on: "push"
jobs:
  install:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        - exclude:
            node-version: 14
            operating-system: macos-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install Dependencies"
        run: npm install
      - name: "Cache Node Modules"
        uses: actions/cache@v3
        with:
          path: npm_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  test:
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: npm_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Run Tests"
        run: npm run test
  lint:
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: npm_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Run Lint"
        run: npm run lint
  deploy:
    needs: [test, lint]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: npm_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Deploy to Production"
        run: echo "deploying to production..."
