name: "Test and Deploy"
on: "push"
jobs:
  install:
    uses: ./.github/workflows/install.yaml
  test:
    needs: install
    runs-on: ${{ needs.install.outputs.operating-system }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Run Tests"
        run: npm run test
  lint:
    needs: install
    runs-on: ${{ needs.install.outputs.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Run Lint"
        run: npm run lint
  deploy:
    needs: [test, lint, install]
    runs-on: ${{ needs.install.outputs.operating-system }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install Dependencies from Cache"
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Deploy to Production"
        run: echo "deploying to production..."
