name: "Issues information"
on: issues
jobs:
  event_info:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get event information"
        run: echo "Event name ${{ github.event_name }}" |
          echo "Event data ${{ github.event }}"
